# Generated by Django 4.1.2 on 2022-10-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanhiaAerea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'companhias_aereas',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='InstanciaVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida_prevista', models.DateTimeField()),
                ('partida_real', models.DateTimeField()),
                ('chegada_prevista', models.DateTimeField()),
                ('chegada_real', models.DateTimeField()),
                ('estado_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voos.estado')),
            ],
            options={
                'db_table': 'instancias_voos',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('companhia_aerea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voos.companhiaaerea')),
            ],
            options={
                'db_table': 'voos',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField()),
                ('tempo_movimentacao', models.DurationField()),
                ('estado_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_anterior', to='voos.estado')),
                ('estado_posterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_posterior', to='voos.estado')),
                ('instancia_voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voos.instanciavoo')),
            ],
            options={
                'db_table': 'movimentacoes',
            },
        ),
        migrations.AddField(
            model_name='instanciavoo',
            name='voo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voos.voo'),
        ),
    ]
