# Generated by Django 4.1.2 on 2022-11-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voos", "0002_set_correct_on_delete_on_all_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companhiaaerea",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="companhiaaerea",
            name="sigla",
            field=models.CharField(max_length=5, verbose_name="sigla"),
        ),
        migrations.AlterField(
            model_name="instanciavoo",
            name="chegada_prevista",
            field=models.DateTimeField(verbose_name="hora de chegada prevista"),
        ),
        migrations.AlterField(
            model_name="instanciavoo",
            name="chegada_real",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="hora de chegada"
            ),
        ),
        migrations.AlterField(
            model_name="instanciavoo",
            name="estado_atual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="voos.estado",
                verbose_name="estado atual",
            ),
        ),
        migrations.AlterField(
            model_name="instanciavoo",
            name="partida_prevista",
            field=models.DateTimeField(verbose_name="hora de partida prevista"),
        ),
        migrations.AlterField(
            model_name="instanciavoo",
            name="partida_real",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="hora de partida"
            ),
        ),
        migrations.AlterField(
            model_name="instanciavoo",
            name="voo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="voos.voo",
                verbose_name="rota",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="data_movimentacao",
            field=models.DateTimeField(verbose_name="data"),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="estado_anterior",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="voos.estado",
                verbose_name="estado anterior",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="estado_posterior",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="voos.estado",
                verbose_name="estado posterior",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="instancia_voo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="voos.instanciavoo",
                verbose_name="voo",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="tempo_movimentacao",
            field=models.DurationField(
                null=True, verbose_name="intervalo entre movimentações"
            ),
        ),
        migrations.AlterField(
            model_name="voo",
            name="codigo",
            field=models.CharField(
                max_length=6, primary_key=True, serialize=False, verbose_name="código"
            ),
        ),
        migrations.AlterField(
            model_name="voo",
            name="companhia_aerea",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="voos.companhiaaerea",
                verbose_name="companhia aérea",
            ),
        ),
        migrations.AlterField(
            model_name="voo",
            name="destino",
            field=models.CharField(max_length=100, verbose_name="destino"),
        ),
        migrations.AlterField(
            model_name="voo",
            name="origem",
            field=models.CharField(max_length=100, verbose_name="origem"),
        ),
    ]
