# Generated by Django 4.1.2 on 2022-11-11 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0004_alter_instanciavoo_estado_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companhiaaerea',
            name='sigla',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('[A-Z]{3}', 'Sigla da companhia aérea deve ser composta de três caracteres maiúsculos.')], verbose_name='sigla'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[A-Z]{2}[1-9]{4}', 'Código de voo deve ser composto de dois caracteres maiúsculos seguidos de quatro dígitos.')], verbose_name='código'),
        ),
    ]
