# Generated by Django 4.1.2 on 2022-11-18 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0005_alter_companhiaaerea_sigla_alter_voo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[A-Z]{2}[0-9]{4}', 'Código de voo deve ser composto de dois caracteres maiúsculos seguidos de quatro dígitos.')], verbose_name='código'),
        ),
    ]
