# Generated by Django 4.1.2 on 2022-11-25 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0007_alter_estado_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanciavoo',
            name='estado_atual',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='voos.estado', verbose_name='estado atual'),
        ),
    ]
