# Generated by Django 4.1.2 on 2022-11-25 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0008_alter_instanciavoo_estado_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanciavoo',
            name='estado_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='voos.estado', verbose_name='estado atual'),
        ),
        migrations.AlterField(
            model_name='instanciavoo',
            name='partida_prevista',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hora de partida prevista'),
        ),
    ]
